#!/bin/zsh
alias cd..='cd ..'
alias tint2restart='killall -SIGUSR1 tint2'
alias wpa_supplicant='sudo wpa_supplicant'
alias reboot='sudo reboot'
alias cls='reset'
alias clear='reset'
alias grep='grep --color=always'
alias halt='sudo systemctl halt'
alias ccsm='LC_ALL="en_US.UTF-8" ccsm'
alias sintel='sudo pxp_switch_catalyst intel && sudo systemctl start sddm'
alias samd='sudo pxp_switch_catalyst amd && sudo systemctl start sddm'
alias pb='curl -F c=@- https://ptpb.pw'
alias real-vim='vim'
alias vim='nvim'
alias open='rifle'
alias octave='octave -q --no-gui'
alias kaboom='poweroff'
alias amdgpu='DRI_PRIME=1'
alias clip='xclip -selection clipboard'

# ls
alias l='ls --color=always --show-control-chars'
alias ll='ls --color=always -l -h --show-control-chars'
alias la='ls --color=always -a -h --show-control-chars'
alias lla='ls --color=always -lah --show-control-chars'

# Single Letter commands
alias d='docker'
alias k='kubectl'
alias f='fuck'

# SSH
alias logica='ssh -p 2222 roberto@logica.dyndns.info'

# Git
ga() {
  if [ $# -lt 1 ]; then
    git add .
  else
    git add $@
  fi
}
alias gst='git status'
