#!/bin/zsh
alias cd..='cd ..'
alias tint2restart='killall -SIGUSR1 tint2'
alias wpa_supplicant='sudo wpa_supplicant'
alias reboot='sudo reboot'
alias cls='reset'
alias clear='reset'
alias grep='grep --color=always'
alias halt='sudo systemctl halt'
alias ccsm='LC_ALL="en_US.UTF-8" ccsm'
alias sintel='sudo pxp_switch_catalyst intel && sudo systemctl start sddm'
alias samd='sudo pxp_switch_catalyst amd && sudo systemctl start sddm'
alias vim='nvim'
alias vimf='nvim $(find . | fzf)'
alias open='rifle'
alias octave='octave -q --no-gui'
alias kaboom='poweroff'
alias amdgpu='DRI_PRIME=1'
alias cat='bat --theme TwoDark'
alias yaml='bat --theme TwoDark -l yaml'
alias chmox='chmod +x'

clip() {
  COMMAND="xclip -selection clipboard"
  if [[ "$OSTYPE" =~ "darwin*" ]]; then
    if [ $# -ge 1 ] && [ "$1" = "-o" ]; then
      shift
      COMMAND="pbpaste"
    else
      COMMAND="pbcopy"
    fi
  fi

  $COMMAND $@
}

# ls
alias l='exa --color=always -a --group-directories-first --icons'
alias ls='exa --color=always --group-directories-first --icons'
alias ll='exa --color=always -l --group-directories-first --icons'
alias la='exa --color=always -a --group-directories-first --icons'
alias lla='exa --color=always -la --group-directories-first --icons'

# curl
alias curl='curlie'

# KubeCtl
# alias kx='kubectx'
# alias kn='kubens'

# Single Letter commands
alias d='docker'
alias k='kubectl'
alias f='fuck'
alias t='terraform'

# SSH
alias logica='ssh -p 2222 roberto@server.robertoalegro.com'

# Git
ga() {
  if [ $# -lt 1 ]; then
    git add .
  else
    git add $@
  fi
}
alias gst='git status'
alias gpull='git pull'
alias gpu='git pull'

# Watch with aliases
alias watch='watch '

# Work
alias sprod='ssh -i ~/Documents/work/ops-config/ssh_keys/topfreegames-prod-vpc.pem -l ubuntu'
alias sstag='ssh -i ~/Documents/work/ops-config/ssh_keys/topfreegames-stag-vpc.pem -l ubuntu'
alias kstag='kubectl --context=stag'
alias ki='kubectl --context=infra'
alias kpus='kubectl --context=kube-prod-us-cilium.tfgco.com'
alias koldprod='kubectl --context=kube-prod.tfgco.com'

# Env vars
if [[ ! -z $commands[direnv] ]]; then
  alias tmux='direnv exec / tmux'
fi
