#!/bin/zsh
alias cd..='cd ..'
alias tint2restart='killall -SIGUSR1 tint2'
alias wpa_supplicant='sudo wpa_supplicant'
alias reboot='sudo reboot'
alias cls='reset'
alias clear='reset'
alias grep='grep --color=always'
alias halt='sudo systemctl halt'
alias ccsm='LC_ALL="en_US.UTF-8" ccsm'
alias sintel='sudo pxp_switch_catalyst intel && sudo systemctl start sddm'
alias samd='sudo pxp_switch_catalyst amd && sudo systemctl start sddm'
alias pb='curl -F c=@- https://ptpb.pw'
alias vim='nvim'
alias vimf='nvim $(find . | fzf)'
alias open='rifle'
alias octave='octave -q --no-gui'
alias kaboom='poweroff'
alias amdgpu='DRI_PRIME=1'
alias clip='xclip -selection clipboard'
alias cat='bat --theme TwoDark'

# ls
alias l='exa --color=always -a --group-directories-first'
alias ls='exa --color=always --group-directories-first'
alias ll='exa --color=always -l --group-directories-first'
alias la='exa --color=always -a --group-directories-first'
alias lla='exa --color=always -la --group-directories-first'

# Single Letter commands
alias d='docker'
alias k='kubectl'
alias f='fuck'

# SSH
alias logica='ssh -p 2222 roberto@server.robertoalegro.com'

# Git
ga() {
  if [ $# -lt 1 ]; then
    git add .
  else
    git add $@
  fi
}
alias gst='git status'
alias gpull='git pull'
alias gpu='git pull'
