#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#


#
# Editors
#

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'
export TERMINAL='kitty'
export GOPATH="$HOME/documents/programming/GO"
export CARGO_PATH="$HOME/.cargo"

# Use ag for FZF
if [[ ! -z $commands[ag] ]]; then
  export FZF_DEFAULT_COMMAND='ag -g ""'
fi

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
	export BROWSER='open'
  export GOPATH="$HOME/Documents/work/GO"
  export GNUBINSPATH="$(find /usr/local/opt -type d -follow -name gnubin -print | paste -sd: -)";
fi

#
# Language
#

if [[ -z "$LANG" ]]; then
	export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
/usr/local/{bin,sbin}
~/.local/{bin,sbin}
$path
)

# Go binaries
if [ -d $GOPATH/bin/ ]; then
  path=(
  $GOPATH/bin
  $path
  )
fi

# Kubectl plugins
KREW_DIR=${KREW_ROOT:-$HOME/.krew}
if [ -d $KREW_DIR/bin ]; then
  path=(
  $KREW_DIR/bin
  $path
  )
fi

# Rust Binaries
if [ -d  $CARGO_PATH/bin/ ]; then
  path=(
  $CARGO_PATH/bin/
  $path
  )
fi

# Composer binaries
if which php >/dev/null && which composer >/dev/null; then
	path=(
	$HOME/.config/composer/vendor/bin
	$path
	)
fi

# Ruby gems
if which ruby >/dev/null && which gem >/dev/null; then
	path=(
	`ruby -e 'puts Gem.user_dir'`/bin
	$path
	)
	#PATH="$PATH:$(ruby -e 'puts Gem.user_dir')/bin"
fi

# NodeJS jshint
if which npm >/dev/null; then
	path=(
	`npm root`/jshint/bin
	$path
	)
	#PATH="$PATH:$(npm root)/jshint/bin"
fi

# Heroku
if which heroku >/dev/null; then
	#PATH="$PATH:/usr/local/heroku/bin"
	path=(
	/usr/local/heroku/bin
	$path
	)
fi

# My scripts
SCRIPTS_PATH="$HOME/scripts"
if [[ -d $SCRIPTS_PATH ]]; then
	#PATH="$PATH:$SCRIPTS_PATH"
	path=(
	$SCRIPTS_PATH
	$path
	)
fi

# OCaml
OPAM_PATH="$HOME/.opam"
if [[ -d $OPAM_PATH ]] && which opam >/dev/null; then
  eval $(opam env)
fi

# Cuda
CUDA_BIN_PATH="/opt/cuda/bin"
if [[ -d $CUDA_PATH ]]; then
	#PATH="$PATH:$CUDA_BIN_PATH"
	path=(
	$CUDA_BIN_PATH
	$path
	)
fi

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
	export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi


# Use GNUBINS in MacOS
if [[ -n "$GNUBINSPATH" ]]; then
  PATH="$GNUBINSPATH:$PATH"
fi

# Rust ESP support
if [[ -f "$HOME/export-esp.sh" ]]; then
  source "$HOME/export-esp.sh"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
	export TMPDIR="/tmp/$LOGNAME"
	mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

export TERM=tmux-256color

# Export monitor for polybar
if [ "$(hostname)" = "Wild-Roberto" ]; then
  export MONITOR=eDP-1
else
  export MONITOR=HDMI-1
fi
# Doesn't work because it runs before X
# export MONITOR=$(xrandr --listactivemonitors | tail -1 | awk '{print $4}')
