#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
	export BROWSER='open'
fi

#
# Editors
#

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'
export TERMINAL='kitty'

#
# Language
#

if [[ -z "$LANG" ]]; then
	export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
/usr/local/{bin,sbin}
$path
)

# Composer binaries
if which php >/dev/null && which composer >/dev/null; then
	path=(
	$HOME/.config/composer/vendor/bin
	$path
	)
fi

# Ruby gems
if which ruby >/dev/null && which gem >/dev/null; then
	path=(
	`ruby -e 'puts Gem.user_dir'`/bin
	$path
	)
	#PATH="$PATH:$(ruby -e 'puts Gem.user_dir')/bin"
fi

# NodeJS jshint
if which npm >/dev/null; then
	path=(
	`npm root`/jshint/bin
	$path
	)
	#PATH="$PATH:$(npm root)/jshint/bin"
fi

# Heroku
if which heroku >/dev/null; then
	#PATH="$PATH:/usr/local/heroku/bin"
	path=(
	/usr/local/heroku/bin
	$path
	)
fi

# My scripts
SCRIPTS_PATH="$HOME/scripts"
if [[ -d SCRIPTS_PATH ]]; then
	#PATH="$PATH:$SCRIPTS_PATH"
	path=(
	$SCRIPTS_PATH
	$path
	)
fi

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
	export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
	export TMPDIR="/tmp/$LOGNAME"
	mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

export TERM=tmux-256color
