#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
	source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Ruby gems
if which ruby >/dev/null && which gem >/dev/null; then
	PATH="$PATH:$(ruby -rubygems -e 'puts Gem.user_dir')/bin"
fi

# NodeJS jshint
if which npm >/dev/null; then
	PATH="$PATH:$(npm root)/jshint/bin"
fi

# Heroku
if which heroku >/dev/null; then
	PATH="$PATH:/usr/local/heroku/bin"
fi

# My scripts
SCRIPTS_PATH="$HOME/scripts"
if [[ -d SCRIPTS_PATH ]]; then
	PATH="$PATH:$SCRIPTS_PATH"
fi

# SSH agent
eval `ssh-agent -s`

VIMRC="~/.config/nvim/init.vim"
export __GLVND_DISALLOW_PATCHING=1
